#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Configuring NGINX web server..."

# Create a dedicated NGINX config
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd

mkdir -p /var/log/$app
chown -R $app:$app "/var/log/$app"

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate

yunohost service add $app --log="/var/log/$app/$app.log"

#=================================================
# SPECIFIC SETUP
#=================================================
# INSTALL PYTHON DEPENDENCIES
#=================================================
ynh_script_progression "Installing Python dependencies in venv..."

pushd $install_dir
    python3 -m venv venv
    venv/bin/pip install --upgrade pip
    venv/bin/pip install --upgrade pyyaml
    venv/bin/pip install --pre pyload-ng[all]
popd

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service=$app --action="start"  --wait_until="Proxy listening"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
